In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, random, shutil, time
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import sys

from datetime import datetime

In [2]:
starting_dir = os.getcwd()
print (starting_dir)

/Users/kimd999/research/script_not_in_dropbox/srpAnalytics/code/latest/1_tall2wide/1_before_tall2wide/phase_I_II/LPR/0_basic_raw_data_qc


In [3]:
# before merging
#complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/older/before_merging/old/before_Lisa_fix/tall/archive/before_updating_plate_id_for_TX/344_zf_LPR_data_phase_1_2_2020JUNE25.csv'

# after merging
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/after_merging/tall/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed_merged.csv'

df = pd.read_csv(complete_input_file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

chemical.id  conc  plate.id well timepoint  value
0         1030   NaN       NaN  NaN        t0    NaN
1         1030   0.0    9414.0  A06        t0    0.0
2         1030   0.0    9414.0  A12        t0    2.7
3         1030   0.0    9414.0  B06        t0    0.5
4         1030   0.0    9414.0  B12        t0    0.0

344

In [54]:
# divide per chemical.id
    
chemical_id_from_here = np.unique(df['chemical.id'])

full_devel = "full"
#full_devel = "devel"

if (full_devel == "devel"):
    randomly_chosen = random.sample(set(chemical_id_from_here), 2)
    chemical_id_from_here = []
    for i in range(len(randomly_chosen)):
        chemical_id_from_here.append(randomly_chosen[i])

chemical_id_from_here = [53]

for chemical_id in chemical_id_from_here:
    print ("\n", chemical_id)
    df_per_chemical = df.loc[df['chemical.id'] == chemical_id]
    #display(df_per_chemical.head())

    output_filename = "df_per_chemical_" + str(chemical_id) + ".csv"
    df_per_chemical.to_csv(output_filename,index=False)
'''
for chemical_index in chemical_id_from_here:
    print("\nchemical_index:" + str(chemical_index))
    df_per_chemical = df.loc[df['chemical.id'] == chemical_index]
    display(df_per_chemical.head())

    now = datetime.now()

    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
'''    
display(df_per_chemical.head())
print ("extraction per chemical is done.") 



 53


chemical.id bottle.id  conc  plate.id well timepoint  value
4236920           53    C96423   NaN       NaN  NaN        t0    NaN
4255304           53    C96423   0.0    9289.0  A06        t0    0.0
4255305           53    C96423   0.0    9289.0  A12        t0    0.0
4255306           53    C96423   0.0    9289.0  B06        t0    0.0
4255307           53    C96423   0.0    9289.0  B12        t0    0.0

extraction per chemical is done.


In [30]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/after_merging/wide/04_28_2021/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed_full_240_timepoints_wide_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

chemical.id  plate.id well chemical_plate_well  conc   t0   t1   t2   t3  \
0       1030.0    9414.0  A01     1030_9414.0_A01  50.0  0.0  0.0  0.0  0.0   
1       1030.0    9414.0  A02     1030_9414.0_A02  35.6  0.0  1.2  0.0  0.0   
2       1030.0    9414.0  A03     1030_9414.0_A03  11.2  0.0  0.0  0.0  0.0   
3       1030.0    9414.0  A04     1030_9414.0_A04   5.0  0.0  1.7  0.0  1.0   
4       1030.0    9414.0  A05     1030_9414.0_A05   1.0  3.0  0.0  0.0  0.0   

    t4  ...  t230  t231  t232  t233  t234  t235  t236  t237  t238  t239  
0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1  0.0  ...   0.0   0.0   3.1  12.7  16.3  11.7  13.9  16.0  20.0  18.6  
2  0.0  ...   0.0   0.0   1.6   6.4   7.1   7.6  12.2  13.7   5.5   0.0  
3  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4  0.0  ...   1.8  14.4  24.2  29.3  16.7  30.8   2.3   0.0   6.4   8.7  

[5 rows x 245 columns]

1348

array([53., 54., 56., ..., nan, nan, nan])

In [31]:
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]

display(rows_with_NaN.head())
display(rows_with_NaN.tail())
display(len(rows_with_NaN))

chemical.id  plate.id well chemical_plate_well  conc   t0   t1   t2   t3  \
0       1030.0    9414.0  A01     1030_9414.0_A01  50.0  0.0  0.0  0.0  0.0   
1       1030.0    9414.0  A02     1030_9414.0_A02  35.6  0.0  1.2  0.0  0.0   
2       1030.0    9414.0  A03     1030_9414.0_A03  11.2  0.0  0.0  0.0  0.0   
3       1030.0    9414.0  A04     1030_9414.0_A04   5.0  0.0  1.7  0.0  1.0   
4       1030.0    9414.0  A05     1030_9414.0_A05   1.0  3.0  0.0  0.0  0.0   

    t4  ...  t230  t231  t232  t233  t234  t235  t236  t237  t238  t239  
0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1  0.0  ...   0.0   0.0   3.1  12.7  16.3  11.7  13.9  16.0  20.0  18.6  
2  0.0  ...   0.0   0.0   1.6   6.4   7.1   7.6  12.2  13.7   5.5   0.0  
3  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4  0.0  ...   1.8  14.4  24.2  29.3  16.7  30.8   2.3   0.0   6.4   8.7  

[5 rows x 245 columns]

chemical.id  plate.id well chemical_plate_well  conc   t0   t1   t2  \
45868        965.0    9976.0  H08      965_9976.0_H08  35.6  0.8  0.0  0.0   
45869        965.0    9976.0  H09      965_9976.0_H09  11.2  9.2  0.4  0.0   
45870        965.0    9976.0  H10      965_9976.0_H10   5.0  4.4  4.3  4.3   
45871        965.0    9976.0  H11      965_9976.0_H11   1.0  1.4  2.7  0.0   
45872        965.0    9976.0  H12      965_9976.0_H12   0.0  4.1  0.0  1.8   

        t3   t4  ...  t230  t231  t232  t233  t234  t235  t236  t237  t238  \
45868  0.0  0.0  ...   0.0   0.0   4.4   0.4   0.0   0.0   0.0   0.0   0.0   
45869  0.2  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   
45870  8.7  4.7  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
45871  0.0  0.0  ...   0.0   0.0   1.6   0.0   0.0   0.0   0.0   0.0   0.0   
45872  6.3  0.0  ...   0.0   0.0   0.0   0.0   8.5  13.6  19.6  10.1  12.7   

       t239  
45868   0.0  
45869   4.9  
45870   0.0  
45871   0.0  
45872  16.0  

[5 rows x 245 columns]

14198

In [32]:
display("before dropna, len(df):"+str(len(df)))
df = df.dropna(how='any')
display("after dropna,  len(df):"+str(len(df)))

'before dropna, len(df):46449'

'after dropna,  len(df):32251'

In [36]:
df['chemical.id'] = df['chemical.id'].astype(int)
    
display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

df['plate.id'] = df['plate.id'].astype(str)
try:
    df['plate.id'] = df['plate.id'].astype(float)
    df['plate.id'] = df['plate.id'].astype(int)
except:
    pass

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

display (df.head())

134

array([  54,   56,   58,   61,   62,   63,   64,   65,  129,  155,  220,
        246,  247,  248,  251,  252,  281,  283,  285,  296,  360,  365,
        381,  384,  392,  409,  412,  418,  441,  500,  501,  502,  503,
        504,  514,  517,  596,  597,  601,  602,  618,  628,  667,  674,
        689,  691,  746,  747,  769,  770,  771,  774,  775,  778,  946,
        947,  948,  952,  961,  966,  998, 1031, 1105, 1114, 1161, 1163,
       1166, 1171, 1172, 1174, 1175, 1177, 1182, 1211, 1221, 1307, 1354,
       1370, 1371, 1595, 1603, 1611, 1612, 1613, 1614, 1616, 1619, 1620,
       1629, 1651, 1670, 1770, 1854, 1861, 1930, 1965, 1967, 2058, 2067,
       2142, 2323, 2532, 2601, 2635, 2637, 2739, 2740, 2751, 2770, 2778,
       2813, 2973, 3002, 3004, 3005, 3091, 3102, 3114, 3138, 3144, 3147,
       3151, 3273, 3411, 3412, 3413, 3689, 3690, 3757, 3758, 3759, 3760,
       3859, 3860])

334

array([ 9302,  9796,  9797,  9844,  9845,  9980,  9981, 10090, 10091,
       10192, 10250, 10251, 10253, 10255, 10465, 10467, 10520, 10531,
       10534, 10535, 10591, 10593, 10938, 10940, 10945, 10970, 10996,
       10997, 10998, 10999, 11042, 11044, 11069, 11070, 11076, 11176,
       11479, 11542, 11620, 11622, 11735, 11928, 11987, 11991, 11998,
       11999, 12003, 12008, 12085, 12099, 12317, 12362, 12388, 12410,
       12412, 12414, 12439, 12441, 12442, 12446, 12447, 12512, 12515,
       12517, 12546, 12552, 12563, 12564, 12567, 12570, 12571, 12594,
       12789, 12798, 12805, 12806, 12820, 12825, 12826, 12838, 12839,
       12841, 12843, 12858, 12859, 12862, 12865, 12866, 12873, 12874,
       12877, 12882, 12884, 12886, 12889, 12890, 12891, 12892, 12897,
       12902, 12904, 12935, 12953, 13019, 13021, 13114, 13115, 13122,
       13123, 13155, 13157, 13217, 13219, 13220, 13226, 13227, 13237,
       13238, 13240, 13250, 13251, 13253, 13255, 13278, 13304, 13305,
       13306, 13319,

chemical.id  plate.id well chemical_plate_well  conc      t0      t1  \
192         1031     13522  A01    1031_13522.0_A01  50.0  19.523  13.706   
193         1031     13522  A02    1031_13522.0_A02  35.6   0.000   0.000   
194         1031     13522  A03    1031_13522.0_A03  11.2   0.779   3.014   
195         1031     13522  A04    1031_13522.0_A04   5.0   0.000   0.000   
196         1031     13522  A05    1031_13522.0_A05   1.0   0.000   0.000   

         t2      t3      t4  ...   t230    t231    t232   t233   t234   t235  \
192   2.196   0.000  12.619  ...  9.135  14.572  11.551  0.415  1.246  8.556   
193   0.000   0.000   0.000  ...  0.000   0.000   0.000  0.000  0.000  0.000   
194  17.207  11.661   0.699  ...  0.000   0.000   0.000  0.000  0.000  0.000   
195   0.000   0.000   0.000  ...  0.000   0.000   0.000  0.000  0.000  0.000   
196   0.000   0.000   0.000  ...  0.000   0.000   0.000  0.000  0.000  0.000   

       t236    t237    t238   t239  
192  14.134  19.201  30.299  20.82  
193   0.000   0.000   0.000   0.00  
194   0.000   0.000   0.000   0.00  
195   0.000   0.000   0.000   0.00  
196   0.000   0.000   0.000   0.00  

[5 rows x 245 columns]

In [21]:
len_timepoint = []

chemical_id_from_here = np.unique(df['chemical.id'])
        
total_number_of_chemicals_to_processed = len(chemical_id_from_here)
number_of_chemicals_processed = 0

for chemical_index in chemical_id_from_here:
    df_chemical = df.loc[df['chemical.id'] == chemical_index,:]
    #print("chemical_index:" + str(chemical_index))
    
    len_timepoint.append(len(np.unique(df_chemical['timepoint'])))
    
    #number_of_chemicals_processed += 1
    #write_this = str(number_of_chemicals_processed) + " chemicals processed out of " + str(total_number_of_chemicals_to_processed)
    #print(write_this)


KeyError: 'timepoint'

In [22]:
ds = pd.Series({"Column": len_timepoint})
plt.figure(figsize=(8,4))
#plt.savefig("distribute.png")
sns.countplot(x="Column", data=ds)

ValueError: min() arg is an empty sequence

<Figure size 576x288 with 0 Axes>

In [ ]:
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/before_merging/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [11]:


file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/after_Lisa_fix/full/tall/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
display(df.head())
display(len(df))

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))

chemical.id  conc  plate.id well endpoint  value bottle.id
0         1030   NaN       NaN  NaN       t0    NaN       NaN
1         1030   0.0    9414.0  A06       t0    0.0       NaN
2         1030   0.0    9414.0  A12       t0    2.7       NaN
3         1030   0.0    9414.0  B06       t0    0.5       NaN
4         1030   0.0    9414.0  B12       t0    0.0       NaN

11610480

344