In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, random, shutil, time
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import sys

from datetime import datetime

In [2]:
starting_dir = os.getcwd()
print (starting_dir)

/Users/kimd999/Dropbox/script/python/srpAnalytics/code/latest/1_tall2wide/1_before_tall2wide


In [25]:
complete_input_file_path = "/Users/kimd999/research/projects/Katrina/per_each_data/extracts/input/latest/tall/ZF_120_SRP_Sample_Extracts_with_Dilution_Factors_2021MAY21.csv"
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

df['plate.id'] = df['plate.id'].astype('str')

display(df.head())
display(df.tail())
display(df.shape)

#display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (type(df['chemical.id']))
#pandas.core.series.Series

#display (df['chemical.id'].dtypes)
#dtype('int64')

#display (np.unique(df['plate.id']))
#display (len(np.unique(df['plate.id'])))

chemical.id bottle.id  conc plate.id well      date endpoint  value
0          101    C51699   0.0    10021  A06  20151113     MO24    0.0
1          101    C51699   0.0    10021  B06  20151113     MO24    0.0
2          101    C51699   0.0    10021  C06  20151113     MO24    0.0
3          101    C51699   0.0    10021  D06  20151113     MO24    1.0
4          101    C51699   0.0    10021  E06  20151113     MO24    0.0

chemical.id bottle.id  conc plate.id well      date endpoint  value
570234         3334   C295432  0.01    16889  D08  20180302     DNC_    0.0
570235         3334   C295432  0.01    16889  E08  20180302     DNC_    0.0
570236         3334   C295432  0.01    16889  F08  20180302     DNC_    0.0
570237         3334   C295432  0.01    16889  G08  20180302     DNC_    0.0
570238         3334   C295432  0.01    16889  H08  20180302     DNC_    0.0

(570239, 8)

array([ 101,  102,  103,  131,  132,  177,  452,  495,  669,  719,  723,
        744,  797,  798,  799,  800,  839,  858,  889,  890,  891, 1004,
       1008, 1009, 1035, 1036, 1037, 1038, 1426, 1427, 1428, 1429, 1431,
       1432, 1456, 1458, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521,
       1864, 2066, 2071, 2072, 2235, 2236, 2791, 2792, 2793, 2794, 2795,
       2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806,
       2807, 2808, 2809, 2810, 2917, 2918, 2921, 3053, 3322, 3324, 3325,
       3326, 3328, 3329, 3330, 3331, 3332, 3334])

In [34]:
full_devel = "full"
#full_devel = "devel"

if (full_devel == "full"):
    chemical_id_from_here = np.unique(df['chemical.id'])
else:
    chemical_id_from_here = [101]

total_number_of_chemicals_to_process = len(chemical_id_from_here)

for chemical_id in chemical_id_from_here:
    print(f"\nchemical_id:{chemical_id}")
    df_per_chemical_id = df.loc[df['chemical.id'] == chemical_id,['chemical.id', 'conc']]
    #display(df_per_chemical_id.head())
    df_per_chemical_id.sort_values(by=['conc'])
    display(np.unique(df_per_chemical_id['conc']))
    display(max(df_per_chemical_id['conc']))
    display(min(df_per_chemical_id['conc']))



chemical_id:101


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:102


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:103


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:131


array([0.     , 0.00125, 0.0025 , 0.005  , 0.01   ])

0.01

0.0


chemical_id:132


array([0.     , 0.00125, 0.0025 , 0.005  , 0.01   ])

0.01

0.0


chemical_id:177


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:452


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:495


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:669


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:719


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:723


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:744


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:797


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:798


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:799


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:800


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:839


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:858


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:889


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:890


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:891


array([0.      , 0.000625, 0.00125 , 0.0025  , 0.005   , 0.01    ])

0.01

0.0


chemical_id:1004


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1008


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1009


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1035


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1036


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1037


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1038


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1426


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1427


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1428


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1429


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1431


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1432


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1456


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1458


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:1514


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1515


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1516


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1517


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1518


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1519


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1520


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1521


array([0.    , 0.0001, 0.001 , 0.0025, 0.005 , 0.01  ])

0.01

0.0


chemical_id:1864


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2066


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2071


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2072


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2235


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2236


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2791


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2792


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2793


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2794


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2795


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2796


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2797


array([0.    , 0.0067, 0.0075, 0.008 ])

0.008

0.0


chemical_id:2798


array([0.0e+00, 8.0e-05, 4.0e-04, 2.0e-03, 6.7e-03, 7.5e-03, 8.0e-03,
       1.0e-02])

0.01

0.0


chemical_id:2799


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2800


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2801


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2802


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2803


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2804


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2805


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2806


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2807


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2808


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2809


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2810


array([0.e+00, 8.e-05, 4.e-04, 2.e-03, 1.e-02])

0.01

0.0


chemical_id:2917


array([0.     , 0.00063, 0.0016 , 0.0025 , 0.0034 , 0.0044 , 0.0053 ,
       0.0063 , 0.0072 , 0.0081 , 0.0091 , 0.01   ])

0.01

0.0


chemical_id:2918


array([0.     , 0.00063, 0.0016 , 0.0025 , 0.0034 , 0.0044 , 0.0053 ,
       0.0063 , 0.0072 , 0.0081 , 0.0091 , 0.01   ])

0.01

0.0


chemical_id:2921


array([0.     , 0.00063, 0.0016 , 0.0025 , 0.0034 , 0.0044 , 0.0053 ,
       0.0063 , 0.0072 , 0.0081 , 0.0091 , 0.01   ])

0.01

0.0


chemical_id:3053


array([0., 5.])

5.0

0.0


chemical_id:3322


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3324


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3325


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3326


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3328


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3329


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3330


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3331


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3332


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0


chemical_id:3334


array([0.     , 0.00133, 0.0033 , 0.0066 , 0.01   ])

0.01

0.0

In [19]:
df_grouped = df.groupby(['chemical.id'])
display(len(df_grouped))
display(df_grouped.head())

84

chemical.id bottle.id  conc plate.id well      date endpoint  value
0              101    C51699   0.0    10021  A06  20151113     MO24    0.0
1              101    C51699   0.0    10021  B06  20151113     MO24    0.0
2              101    C51699   0.0    10021  C06  20151113     MO24    0.0
3              101    C51699   0.0    10021  D06  20151113     MO24    1.0
4              101    C51699   0.0    10021  E06  20151113     MO24    0.0
...            ...       ...   ...      ...  ...       ...      ...    ...
24601         3334   C295432   0.0    16888  A06  20180302     MO24    0.0
24602         3334   C295432   0.0    16888  B06  20180302     MO24    0.0
24603         3334   C295432   0.0    16888  C06  20180302     MO24    0.0
24604         3334   C295432   0.0    16888  D06  20180302     MO24    1.0
24605         3334   C295432   0.0    16888  E06  20180302     MO24    0.0

[420 rows x 8 columns]

In [24]:
display (np.unique(df_grouped['conc']))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
a=b

In [8]:
# tall
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/behavior/LPR/tall/Tanguay_Phase_3_zf_LPR_data_PNNL_2021MAR23.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

chemical.id      bottle.id  conc  plate.id well variable      value
0          234  NTP DNT 91-A1   0.0     14389  H01       t0  17.223000
1          234  NTP DNT 91-A1   0.0     14389  H02       t0  12.876000
2          234  NTP DNT 91-A1   0.0     14389  H03       t0  24.156000
3          234  NTP DNT 91-A1   0.0     14389  H04       t0  31.421999
4          234  NTP DNT 91-A1   0.0     14389  H05       t0  36.917999

215

array([ 234,  275,  280,  385,  397,  443,  467,  505,  588,  595,  622,
        660,  692,  699,  725,  726,  947,  949,  955, 1016, 1017, 1031,
       1155, 1174, 1175, 1178, 1179, 1182, 1189, 1209, 1213, 1214, 1215,
       1216, 1220, 1222, 1241, 1312, 1315, 1371, 1430, 1595, 1601, 1607,
       1610, 1611, 1624, 1626, 1642, 1651, 1830, 1855, 1898, 1925, 1947,
       2076, 2090, 2110, 2151, 2180, 2192, 2240, 2323, 2358, 2585, 2587,
       2589, 2590, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2602, 2635,
       2636, 2650, 2685, 2686, 2715, 2739, 2821, 2973, 2994, 3007, 3056,
       3133, 3136, 3189, 3191, 3766, 3771, 3853, 4336, 4337, 4338, 4339,
       4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349, 4350,
       4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361,
       4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372,
       4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382, 4383,
       4384, 4385, 4386, 4387, 4388, 4390, 4391, 43

In [7]:
#wide
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/behavior/LPR/wide/Tanguay_Phase_3_zf_LPR_data_PNNL_2021_wide_t0_t239_devel_w_240_endpoints.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

chemical.id  plate.id well chemical_plate_well  conc      t0   t1   t2  \
0          234     14389  A01       234_14389_A01  67.0   5.480  0.0  0.0   
1          234     14389  A02       234_14389_A02  67.0  32.079  0.0  0.0   
2          234     14389  A03       234_14389_A03  67.0  13.307  0.0  0.0   
3          234     14389  A04       234_14389_A04  67.0   5.473  0.0  0.0   
4          234     14389  A05       234_14389_A05  67.0  23.419  0.0  0.0   

    t3   t4  ...    t230    t231   t232   t233   t234    t235    t236    t237  \
0  0.0  0.0  ...   0.000   0.000  0.000  0.000  0.000   0.000   2.281   0.000   
1  0.0  0.0  ...   0.000   0.000  0.000  0.000  0.618   1.341   1.430   0.000   
2  0.0  0.0  ...  13.011  11.341  4.929  7.515  4.945  10.594   5.991   5.906   
3  0.0  0.0  ...   0.000   0.000  0.000  0.000  0.000   1.580  21.592  16.256   
4  0.0  0.0  ...   0.000   0.000  0.000  0.000  0.000   3.056   1.710   0.000   

    t238    t239  
0  0.123   0.000  
1  0.000   0.000  
2  9.567  15.081  
3  0.000   0.000  
4  0.000   0.000  

[5 rows x 245 columns]

1

array([234])

In [4]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'

In [ ]:
# count nan_0_1_data
nan_count = 0
zero_count = 0
one_count = 0
total_count = 0
for (columnName, columnData) in reformatted.iteritems(): 
    if (columnName == "chemical.id") or (columnName == "plate.id") or (columnName == "well") or (columnName == "chemical_plate_well") or (columnName == "conc"):
        continue
#    print('Colunm Name : ', columnName) 
#    print('Column Contents : ', columnData.values[i])
#    print (len(columnData.values))
    for i in range(len(columnData.values)):
        total_count += 1
        if (str(columnData.values[i]) == "nan"):
            nan_count += 1
        elif (str(columnData.values[i]) == "0.0"):
            zero_count += 1
        elif (str(columnData.values[i]) == "1.0"):
            one_count += 1
#        print('Column Contents : ', columnData.values[i])
print ("nan_count:" + str(nan_count))
print ("zero_count:" + str(zero_count))
print ("one_count:" + str(one_count))
print ("total_count:" + str(total_count))


In [ ]:
# divide per chemical.id
    
chemical_id_from_here = np.unique(df['chemical.id'])

full_devel = "full"
#full_devel = "devel"

if (full_devel == "devel"):
    randomly_chosen = random.sample(set(chemical_id_from_here), 2)
    chemical_id_from_here = []
    for i in range(len(randomly_chosen)):
        chemical_id_from_here.append(randomly_chosen[i])

chemical_id_from_here = [53]

for chemical_id in chemical_id_from_here:
    print ("\n", chemical_id)
    df_per_chemical = df.loc[df['chemical.id'] == chemical_id]
    #display(df_per_chemical.head())

    output_filename = "df_per_chemical_" + str(chemical_id) + ".csv"
    df_per_chemical.to_csv(output_filename,index=False)
'''
for chemical_index in chemical_id_from_here:
    print("\nchemical_index:" + str(chemical_index))
    df_per_chemical = df.loc[df['chemical.id'] == chemical_index]
    display(df_per_chemical.head())

    now = datetime.now()

    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
'''    
display(df_per_chemical.head())
print ("extraction per chemical is done.") 


In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/after_merging/wide/04_28_2021/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed_full_240_timepoints_wide_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

In [ ]:
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]

display(rows_with_NaN.head())
display(rows_with_NaN.tail())
display(len(rows_with_NaN))

In [ ]:
display("before dropna, len(df):"+str(len(df)))
df = df.dropna(how='any')
display("after dropna,  len(df):"+str(len(df)))

In [ ]:
df['chemical.id'] = df['chemical.id'].astype(int)
    
display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

df['plate.id'] = df['plate.id'].astype(str)
try:
    df['plate.id'] = df['plate.id'].astype(float)
    df['plate.id'] = df['plate.id'].astype(int)
except:
    pass

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

display (df.head())

In [ ]:
len_timepoint = []

chemical_id_from_here = np.unique(df['chemical.id'])
        
total_number_of_chemicals_to_processed = len(chemical_id_from_here)
number_of_chemicals_processed = 0

for chemical_index in chemical_id_from_here:
    df_chemical = df.loc[df['chemical.id'] == chemical_index,:]
    #print("chemical_index:" + str(chemical_index))
    
    len_timepoint.append(len(np.unique(df_chemical['timepoint'])))
    
    #number_of_chemicals_processed += 1
    #write_this = str(number_of_chemicals_processed) + " chemicals processed out of " + str(total_number_of_chemicals_to_processed)
    #print(write_this)


In [ ]:
ds = pd.Series({"Column": len_timepoint})
plt.figure(figsize=(8,4))
#plt.savefig("distribute.png")
sns.countplot(x="Column", data=ds)

In [ ]:
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/before_merging/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [ ]:


file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/after_Lisa_fix/full/tall/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
display(df.head())
display(len(df))

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))