In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, random, shutil, time
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import sys

from datetime import datetime

In [2]:
starting_dir = os.getcwd()
print (starting_dir)

/Users/kimd999/research/script_not_in_dropbox/srpAnalytics/code/latest/2_bmd/1_before_bmd/phase_I_II/morpho


In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/morpho/wide/2_after_fixing_MO24/zf_morphology_data_335_chemicals_2020DEC16_fixed_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [3]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/morpho/wide/2_after_fixing_MO24/zf_morphology_data_335_chemicals_2020DEC16_fixed_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

chemical.id plate.id well chemical_plate_well  conc  AXIS  BRAI  CFIN  \
0           53     9289  A01         53_9289_A01  50.0   NaN   NaN   NaN   
1           53     9289  A02         53_9289_A02  35.6   0.0   0.0   0.0   
2           53     9289  A03         53_9289_A03  11.2   0.0   0.0   0.0   
3           53     9289  A04         53_9289_A04   5.0   1.0   0.0   0.0   
4           53     9289  A05         53_9289_A05   1.0   0.0   0.0   0.0   

   CIRC  DNC_  ...  PE__  PFIN  PIG_  SM24  SNOU  SOMI  SWIM  TRUN  TR__  YSE_  
0   NaN   0.0  ...   NaN   NaN   NaN   0.0   NaN   NaN   NaN   NaN   NaN   NaN  
1   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0  ...   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
4   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 28 columns]

335

array([  53,   54,   56,   57,   58,   60,   61,   62,   63,   64,   65,
         66,   67,   69,   70,  129,  155,  163,  165,  172,  176,  197,
        220,  227,  246,  247,  248,  250,  251,  252,  281,  283,  285,
        286,  295,  296,  297,  332,  337,  338,  339,  342,  355,  357,
        360,  362,  363,  365,  370,  373,  380,  381,  384,  392,  395,
        396,  401,  403,  404,  406,  409,  412,  413,  414,  415,  416,
        417,  418,  419,  420,  421,  441,  447,  448,  470,  471,  472,
        481,  500,  501,  502,  503,  504,  511,  512,  513,  514,  515,
        517,  557,  560,  581,  585,  596,  597,  599,  601,  602,  606,
        607,  609,  618,  628,  629,  667,  674,  689,  691,  694,  696,
        697,  702,  721,  722,  740,  741,  746,  747,  768,  769,  770,
        771,  774,  775,  776,  777,  778,  946,  947,  948,  949,  951,
        952,  961,  965,  966,  998, 1030, 1031, 1105, 1114, 1119, 1161,
       1163, 1166, 1167, 1171, 1172, 1174, 1175, 11

725

array(['10061', '10067', '10075', '10080', '10081', '10083', '10090',
       '10091', '10130', '10142', '10184', '10186', '10188', '10190',
       '10191', '10192', '10193', '10250', '10251', '10253', '10255',
       '10465', '10467', '10520', '10531', '10534', '10535', '10591',
       '10593', '10778', '10779', '10938', '10940', '10945', '10970',
       '10998', '10999', '11034', '11035', '11042', '11044', '11069',
       '11070', '11076', '11102', '11108', '11176', '11479', '11542',
       '11620', '11622', '11735', '11928', '11987', '11991', '11998',
       '11999', '12003', '12008', '12085', '12099', '12106', '12317',
       '12362', '12388', '12412', '12439', '12441', '12442', '12446',
       '12447', '12494', '12496', '12512', '12515', '12517', '12546',
       '12552', '12563', '12564', '12567', '12570', '12571', '12594',
       '12789', '12798', '12805', '12806', '12820', '12825', '12826',
       '12838', '12839', '12841', '12843', '12858', '12859', '12862',
       '12865', '128

In [15]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

chemical.id  plate.id well chemical_plate_well  conc  AXIS  BRN_  CRAN  \
0          725     21511  A01       725_21511_A01   0.0   0.0   0.0   0.0   
1          725     21511  A02       725_21511_A02   0.0   0.0   0.0   0.0   
2          725     21511  A03       725_21511_A03   0.0   0.0   0.0   0.0   
3          725     21511  A04       725_21511_A04   0.0   0.0   0.0   0.0   
4          725     21511  A05       725_21511_A05   0.0   0.0   0.0   0.0   

   DNC_  DP24  EDEM  LTRK  MO24  MORT  MUSC  NC__  SKIN  SM24  TCHR  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

139

array([ 725,  726, 1016, 2585, 2587, 2589, 2590, 2594, 2595, 2596, 2597,
       2598, 2599, 2600, 2685, 2686, 3766, 3771, 3853, 4336, 4337, 4338,
       4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349,
       4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360,
       4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371,
       4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382,
       4383, 4384, 4385, 4386, 4387, 4388, 4390, 4391, 4392, 4393, 4394,
       4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405,
       4406, 4407, 4408, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4417,
       4418, 4419, 4420, 4421, 4422, 4423, 4424, 4425, 4426, 4427, 4428,
       4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439,
       4440, 4441, 4442, 4443, 4444, 4445, 4446, 4447, 4448, 4449, 4450,
       4451, 4452, 4453, 4454, 4455, 4456, 4457])

278

array([21455, 21456, 21457, 21458, 21459, 21460, 21461, 21462, 21463,
       21464, 21467, 21468, 21469, 21470, 21471, 21472, 21473, 21474,
       21475, 21476, 21478, 21479, 21480, 21481, 21482, 21483, 21484,
       21485, 21486, 21488, 21489, 21490, 21492, 21493, 21494, 21495,
       21496, 21497, 21498, 21499, 21500, 21501, 21502, 21503, 21504,
       21505, 21506, 21507, 21508, 21509, 21511, 21512, 21514, 21515,
       21516, 21517, 21518, 21519, 21520, 21521, 21522, 21523, 21524,
       21525, 21526, 21527, 21528, 21529, 21530, 21531, 21532, 21533,
       21534, 21535, 21536, 21537, 21538, 21539, 21540, 21541, 21542,
       21543, 21544, 21545, 21546, 21547, 21548, 21549, 21550, 21551,
       21552, 21553, 21554, 21556, 21557, 21558, 21559, 21560, 21561,
       21562, 21563, 21564, 21565, 21566, 21567, 21568, 21569, 21570,
       21572, 21573, 21574, 21575, 21576, 21577, 21578, 21579, 21585,
       21586, 21587, 21588, 21589, 21590, 21592, 21593, 21603, 21605,
       21606, 21607,

In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)

display(df.head())

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

In [ ]:
# count nan_0_1_data
nan_count = 0
zero_count = 0
one_count = 0
total_count = 0
for (columnName, columnData) in reformatted.iteritems(): 
    if (columnName == "chemical.id") or (columnName == "plate.id") or (columnName == "well") or (columnName == "chemical_plate_well") or (columnName == "conc"):
        continue
#    print('Colunm Name : ', columnName) 
#    print('Column Contents : ', columnData.values[i])
#    print (len(columnData.values))
    for i in range(len(columnData.values)):
        total_count += 1
        if (str(columnData.values[i]) == "nan"):
            nan_count += 1
        elif (str(columnData.values[i]) == "0.0"):
            zero_count += 1
        elif (str(columnData.values[i]) == "1.0"):
            one_count += 1
#        print('Column Contents : ', columnData.values[i])
print ("nan_count:" + str(nan_count))
print ("zero_count:" + str(zero_count))
print ("one_count:" + str(one_count))
print ("total_count:" + str(total_count))


In [ ]:
# divide per chemical.id
    
chemical_id_from_here = np.unique(df['chemical.id'])

full_devel = "full"
#full_devel = "devel"

if (full_devel == "devel"):
    randomly_chosen = random.sample(set(chemical_id_from_here), 2)
    chemical_id_from_here = []
    for i in range(len(randomly_chosen)):
        chemical_id_from_here.append(randomly_chosen[i])

chemical_id_from_here = [53]

for chemical_id in chemical_id_from_here:
    print ("\n", chemical_id)
    df_per_chemical = df.loc[df['chemical.id'] == chemical_id]
    #display(df_per_chemical.head())

    output_filename = "df_per_chemical_" + str(chemical_id) + ".csv"
    df_per_chemical.to_csv(output_filename,index=False)
'''
for chemical_index in chemical_id_from_here:
    print("\nchemical_index:" + str(chemical_index))
    df_per_chemical = df.loc[df['chemical.id'] == chemical_index]
    display(df_per_chemical.head())

    now = datetime.now()

    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
'''    
display(df_per_chemical.head())
print ("extraction per chemical is done.") 


In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/after_merging/wide/04_28_2021/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed_full_240_timepoints_wide_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

In [ ]:
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]

display(rows_with_NaN.head())
display(rows_with_NaN.tail())
display(len(rows_with_NaN))

In [ ]:
display("before dropna, len(df):"+str(len(df)))
df = df.dropna(how='any')
display("after dropna,  len(df):"+str(len(df)))

In [ ]:
df['chemical.id'] = df['chemical.id'].astype(int)
    
display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

df['plate.id'] = df['plate.id'].astype(str)
try:
    df['plate.id'] = df['plate.id'].astype(float)
    df['plate.id'] = df['plate.id'].astype(int)
except:
    pass

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

display (df.head())

In [ ]:
len_timepoint = []

chemical_id_from_here = np.unique(df['chemical.id'])
        
total_number_of_chemicals_to_processed = len(chemical_id_from_here)
number_of_chemicals_processed = 0

for chemical_index in chemical_id_from_here:
    df_chemical = df.loc[df['chemical.id'] == chemical_index,:]
    #print("chemical_index:" + str(chemical_index))
    
    len_timepoint.append(len(np.unique(df_chemical['timepoint'])))
    
    #number_of_chemicals_processed += 1
    #write_this = str(number_of_chemicals_processed) + " chemicals processed out of " + str(total_number_of_chemicals_to_processed)
    #print(write_this)


In [ ]:
ds = pd.Series({"Column": len_timepoint})
plt.figure(figsize=(8,4))
#plt.savefig("distribute.png")
sns.countplot(x="Column", data=ds)

In [ ]:
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/before_merging/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [ ]:


file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/after_Lisa_fix/full/tall/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
display(df.head())
display(len(df))

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))